version: '3.5'

services:
  mysql:
    container_name: mysql
    build:
      context: ./docker/mysql
    volumes:
      - "./db_data:/var/lib/mysql"
    env_file:
      - "src/.env"
    ports:
      - "3306:3306"
    tty: true
    networks:
      - rls_networks

  metadata_service:
    container_name: metadata_service
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - "src/.env"
    tty: true
    depends_on:
      - mysql
    networks:
      - rls_networks
    restart: on-failure:3

networks:
  rls_networks:
    name: rls_networks
    driver: bridge